POST http://localhost:8081/login
Content-Type: application/json

{
    "login": "potolovskaya_eva",
    "password": "1234"
}

###

GET http://localhost:8081/attempt
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibG9naW4iOiJwb3RvbG92c2theWFfZXZhIiwiaWF0IjoxNjExMDc2NTY1LCJleHAiOjE2MTEwNzc0NjV9.q29_JM15XgWjeo0irwfEqFulRyz4QMFAqba49Tw5JrM

###

POST http://localhost:8081/refresh
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibG9naW4iOiJwb3RvbG92c2theWFfZXZhIiwiaWF0IjoxNjEwNzY1MjY2fQ.Eb42CgB4p8kzTqMi53dx0gx03q1twdaWarKjoUwTur0"
}

###

GET http://localhost:8081/users/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibG9naW4iOiJwb3RvbG92c2theWFfZXZhIiwiaWF0IjoxNjEwNzY1MjY2LCJleHAiOjE2MTA3NjcwNjZ9.Sqa6cyJjXT6DlEF2z2SzFQoHkkIByth5l_GsxAsR8

###

GET http://localhost:8081/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibG9naW4iOiJwb3RvbG92c2theWFfZXZhIiwicm9sZSI6ItCj0YfQsNGB0YLQvdC40LoiLCJpYXQiOjE2MTE1NTU2MjN9.5Rw5v2k2_KhD75cFZCDrR4D3R4ioXHcHNYHJybYGNxI

###

GET http://localhost:8081/users/curators
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibG9naW4iOiJwb3RvbG92c2theWFfZXZhIiwicm9sZSI6ItCj0YfQsNGB0YLQvdC40LoiLCJpYXQiOjE2MTE1NTU2MjN9.5Rw5v2k2_KhD75cFZCDrR4D3R4ioXHcHNYHJybYGNxI

###

GET http://localhost:8081/positions
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibG9naW4iOiJwb3RvbG92c2theWFfZXZhIiwicm9sZSI6ItCj0YfQsNGB0YLQvdC40LoiLCJpYXQiOjE2MTE1NTU2MjN9.5Rw5v2k2_KhD75cFZCDrR4D3R4ioXHcHNYHJybYGNxI

###

GET http://localhost:8081/firms/?session_id=1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibG9naW4iOiJwb3RvbG92c2theWFfZXZhIiwicm9sZSI6ItCj0YfQsNGB0YLQvdC40LoiLCJpYXQiOjE2MTE1NTU2MjN9.5Rw5v2k2_KhD75cFZCDrR4D3R4ioXHcHNYHJybYGNxI
