POST http://localhost:8081/login
Content-Type: application/json

{
    "login": "potolovskaya_eva",
    "password": "1234"
}

###

POST http://localhost:8081/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dpbiI6IkJhYTEiLCJwYXNzd29yZCI6IjEyMzQiLCJpYXQiOjE2MTA1ODk1NTl9.C8dY_kn_Pqg7iPZxoQs5bedlJ1doSjzmnQQaZuKNpkw"
}

###

GET http://localhost:8081/users/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibG9naW4iOiJwb3RvbG92c2theWFfZXZhIiwiaWF0IjoxNjEwNzQ5MDQ2LCJleHAiOjE2MTA3NTA4NDZ9.mw4sF7L0EEvcp_LU38cAeEtEQzM47tdKdunZUxBbE3I